#!/bin/sh

#将hx后缀的文件转换为h后缀的文件
#HXCOMM 开头的行为注释行，将被丢弃
#STEXI等开头的行，用于控制flag的变化，变为相反的（如原为1，则变0，反之亦然）
#其它行，按flag处理，如果flag== 1,则输出，否则不输出
hxtoh()
{
    flag=1
    while read -r str; do
        case $str in
            HXCOMM*)
            ;;
            SRST*|ERST*) flag=$(($flag^1))
            ;;
            *)
            test $flag -eq 1 && printf "%s\n" "$str"
            ;;
        esac
    done
}

case "$1" in
"-h") hxtoh ;;
*) exit 1 ;;
esac < "$2"

exit 0
